import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import TopProgressBar from "@/components/TopProgressBar";
import Link from "next/link";
import Image from "next/image";
import { getSettings } from "@/services/result";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const setting = await getSettings()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <TopProgressBar />
        <Navbar />
        <Link
          className="fixed bottom-6 right-6"
          target="_blank"
          href={`https://wa.me/+${setting?.whatsappNumber}`}
        >
          <Image
            className="max-sm:!size-14"
            width={70}
            height={70}
            src="https://i.ibb.co/x8fsyXVj/Whats-App-svg.webp"
            alt="whatsapp"
          />
        </Link>
        <p className="max-w-[1140px] text-center mx-auto mt-4 px-3 pb-4 sm:text-base text-xs font-medium">
          !! DISCLAIMER :-{" "}
          <Link href="https://b1sattaplay.in/" target="_blank" className="text-[#f2295be9] font-bold hover:text-[#f2295b]">http:/B1sattaplay.in</Link> is a
          non-commercial website. Viewing This Website Is Your Own Risk, All The
          Information Shown On Website Is Sponsored And We Warn You That Matka
          Gambling/Satta May Be Banned Or Illegal In Your Country ... , We Are
          Not Responsible For Any Issues Or Scam ... , We Respect All Country
          Rules/Laws ... If You Not Agree With Our Site Disclaimer ... Please
          Quit Our Site Right Now. Thank You.
        </p>
      </body>
    </html>
  );
}
